### ISSUE TITLE
Downloading processed data and pretrained models 

### ISSUE THREAD

**Issue by gmuraleekrishna** [YanyuanQiao/HOP-VLN#1]
Can you please share the code and link to download preprocessed data and pretrained models for your project? I cant find any links for them in your codebase.

**Comment by YanyuanQiao** [comment]
I will upload the data and pretrained models soon.

**Comment by YanyuanQiao** [comment]
> Can you please share the code and link to download preprocessed data and pretrained models for your project? I cant find any links for them in your codebase.

The data is released.
