### ISSUE TITLE
No such file or directory: HOP-VLN/logs/202204151250.log

### ISSUE THREAD

**Issue by wbhwbh** [YanyuanQiao/HOP-VLN#4]
After I run the command `bash run/pretrain.bash` in order to start the program, I get the following error
```
Traceback (most recent call last):
  File "./tasks/pretrain/main.py", line 34, in <module>
    fh = logging.FileHandler(logfile, mode='w')
  File "/remote-home/bhwu/anaconda3/envs/hop/lib/python3.7/logging/__init__.py", line 1041, in __init__
    StreamHandler.__init__(self, self._open())
  File "/remote-home/bhwu/anaconda3/envs/hop/lib/python3.7/logging/__init__.py", line 1070, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/remote-home/bhwu/HOP-VLN/logs/202204151250.log'
```
Why this error appear? And the `logs` directory doesn't even exist. How can I get the `.log` file I need?

Thank you very much!

**Comment by YanyuanQiao** [comment]
> After I run the command `bash run/pretrain.bash` in order to start the program, I get the following error
> 
> ```
> Traceback (most recent call last):
>   File "./tasks/pretrain/main.py", line 34, in <module>
>     fh = logging.FileHandler(logfile, mode='w')
>   File "/remote-home/bhwu/anaconda3/envs/hop/lib/python3.7/logging/__init__.py", line 1041, in __init__
>     StreamHandler.__init__(self, self._open())
>   File "/remote-home/bhwu/anaconda3/envs/hop/lib/python3.7/logging/__init__.py", line 1070, in _open
>     return open(self.baseFilename, self.mode, encoding=self.encoding)
> FileNotFoundError: [Errno 2] No such file or directory: '/remote-home/bhwu/HOP-VLN/logs/202204151250.log'
> ```
> 
> Why this error appear? And the `logs` directory doesn't even exist. How can I get the `.log` file I need?
> 
> Thank you very much!

Hi, this error is because you do not have the '/logs/' directory, I fixed this problem.
