### ISSUE TITLE
KeyError: 'uNb9QFRL6hY_272d5682d2b940e2871c0edec0ead4fd'

### ISSUE THREAD

**Issue by xixizai29** [YanyuanQiao/HOP-VLN#7]
Hi, the author, I encountered some problems in reproducing your project:
When I run the pre training command "bash run/retrain. bash", an error occurs after several steps. The situation is as follows：

You are using 1 GPUs to train!!
/home/sun/anaconda3/envs/hop/lib/python3.7/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Loading image features from img_features/ResNet-152-imagenet.tsv
read_num 0
read_num 1
read_num 2
read_num 3
read_num 4
read_num 5
read_num 6
read_num 7
read_num 8
read_num 9
read_num 10
read_num 11
read_num 12
read_num 13
read_num 14
read_num 15
read_num 16
read_num 17
read_num 18
read_num 19
Loading image features from img_features/ResNet-152-imagenet.tsv
read_num 0
read_num 1
read_num 2
read_num 3
read_num 4
read_num 5
read_num 6
read_num 7
read_num 8
read_num 9
read_num 10
read_num 11
read_num 12
read_num 13
read_num 14
read_num 15
read_num 16
read_num 17
read_num 18
read_num 19
you have loaded 1069620  time steps
Loading image features from img_features/ResNet-152-imagenet.tsv
read_num 0
read_num 1
read_num 2
read_num 3
read_num 4
read_num 5
read_num 6
read_num 7
read_num 8
read_num 9
read_num 10
read_num 11
read_num 12
read_num 13
read_num 14
read_num 15
read_num 16
read_num 17
read_num 18
read_num 19
Loading image features from img_features/ResNet-152-imagenet.tsv
read_num 0
read_num 1
read_num 2
read_num 3
read_num 4
read_num 5
read_num 6
read_num 7
read_num 8
read_num 9
read_num 10
read_num 11
read_num 12
read_num 13
read_num 14
read_num 15
read_num 16
read_num 17
read_num 18
read_num 19
you have loaded 17420  time steps
Iteration:   0%|| 0/8357 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/sun/HOP-VLN-main/tasks/pretrain/main.py", line 762, in <module>
    main()
  File "/home/sun/HOP-VLN-main/tasks/pretrain/main.py", line 727, in main
    global_step, tr_loss = trainval(params, train_dataset, eval_dataset, model, tokenizer)
  File "/home/sun/HOP-VLN-main/tasks/pretrain/main.py", line 179, in trainval
    for step, batch in epoch_iterator:
  File "/home/sun/anaconda3/envs/hop/lib/python3.7/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/home/sun/anaconda3/envs/hop/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/sun/anaconda3/envs/hop/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/home/sun/anaconda3/envs/hop/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/sun/anaconda3/envs/hop/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/sun/HOP-VLN-main/tasks/pretrain/batch_loader.py", line 212, in __getitem__
    output = self.getQuery(query, self.nag_trajs, self.nag_trajs_seq, self.nag_trajs_bnb)
  File "/home/sun/HOP-VLN-main/tasks/pretrain/batch_loader.py", line 477, in getQuery
    feature_1, feature_all = self.feature_store.rollout(scan[t], viewpoint[t], viewindex[t])
  File "/home/sun/HOP-VLN-main/tasks/pretrain/feature.py", line 108, in rollout_single
    feature = self.features[long_id]
KeyError: 'uNb9QFRL6hY_272d5682d2b940e2871c0edec0ead4fd'

Can you help me solve this problem? I would be grateful to you！

**Comment by YanyuanQiao** [comment]
> feature

This problem may be you failed to load the feature. .Maybe you can check whether self.features is None to determine whether the feature loading is successful or not.

**Comment by 2201957** [comment]
@xixizai29 I wonder do you finally solve it, i meet the same problem

**Comment by xixizai29** [comment]
> @xixizai29 I wonder do you finally solve it, i meet the same problem
Hello, it's not resolved yet. I'm planning to start over again. I thought I was the only one who encountered this kind of problem.

**Comment by xixizai29** [comment]
> > feature
> 
> This problem may be you failed to load the feature. .Maybe you can check whether self.features is None to determine whether the feature loading is successful or not.

Hello author, I'm sorry to bother you again. I ran it again and the same issue still exists. I only used PREVALENT data and set it to True, and did not make any other changes. Based on your response, I saw in feature.py that self.features should be in the false state. I don't know which step went wrong. Can you be more specific? Thank you very much.

**Comment by jane735** [comment]
After my debug, I found that the reason for this problem is that there is a wrong path here.

**Comment by xixizai29** [comment]
> After my debug, I found that the reason for this problem is that there is a wrong path here.

Thank you for your reply. Through your reply, I have solved this problem. Thank you very much!
